"""add_oauth_and_email_verification

Revision ID: 079b00e9dddc
Revises: 22b45677041a
Create Date: 2025-12-12 08:11:03.937980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079b00e9dddc'
down_revision = '22b45677041a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first to allow existing rows
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('oauth_id', sa.String(length=255), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE users SET email_verified = FALSE WHERE email_verified IS NULL")
    
    # Now make email_verified NOT NULL
    op.alter_column('users', 'email_verified', nullable=False)
    
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'oauth_id')
    op.drop_column('users', 'oauth_provider')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
