"""add_password_reset_tokens_table

NO-OP despite the name — `password_reset_tokens` is really created by
revision a6d655cbc18c (add_assignment_type_to_task_templates). Kept, empty,
because deployed alembic histories already record it.

Revision ID: 8d23a3796561
Revises: fab16872eb7e
Create Date: 2025-12-12 08:15:30.264655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d23a3796561'
down_revision = 'fab16872eb7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
