"""add_email_verification_tokens_table

Revision ID: fab16872eb7e
Revises: 079b00e9dddc
Create Date: 2025-12-12 08:11:49.011775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab16872eb7e'
down_revision = '079b00e9dddc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
