"""add_assignment_type_to_task_templates

Revision ID: a6d655cbc18c
Revises: phase10_remove_actual
Create Date: 2026-03-02 04:30:21.822547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a6d655cbc18c'
down_revision = 'phase10_remove_actual'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_tokens_id'), 'email_verification_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_email_verification_tokens_token'), 'email_verification_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('budget_categorization_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False, comment="'exact', 'contains', 'startswith', 'regex'"),
    sa.Column('match_field', sa.String(length=50), nullable=False, comment="'payee', 'description', 'both'"),
    sa.Column('pattern', sa.String(length=500), nullable=False, comment='Pattern to match (case-insensitive)'),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Higher priority rules match first'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['budget_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_categorization_rules_family_id'), 'budget_categorization_rules', ['family_id'], unique=False)
    op.create_table('budget_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('goal_type', sa.String(length=50), nullable=False, comment="'spending_limit' or 'savings_target'"),
    sa.Column('target_amount', sa.Integer(), nullable=False, comment='Target amount in cents'),
    sa.Column('period', sa.String(length=50), nullable=False, comment="'monthly', 'quarterly', 'annual'"),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Goal start date'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='Goal end date (null = ongoing)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether goal is currently active'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Human-readable goal name'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['budget_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_goals_family_id'), 'budget_goals', ['family_id'], unique=False)
    op.create_table('budget_recurring_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('payee_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Template name (e.g., 'Monthly Rent')"),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False, comment='Amount in cents (negative=expense, positive=income)'),
    sa.Column('recurrence_type', sa.String(length=50), nullable=False, comment="'daily', 'weekly', 'monthly_dayofmonth', 'monthly_dayofweek'"),
    sa.Column('recurrence_interval', sa.Integer(), nullable=False, comment='Repeat every N periods'),
    sa.Column('recurrence_pattern', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Pattern-specific configuration'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='First occurrence date'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='Last occurrence date (null = ongoing)'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_generated_date', sa.Date(), nullable=True, comment='Last date a transaction was auto-generated'),
    sa.Column('next_due_date', sa.Date(), nullable=True, comment='Next scheduled date'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['budget_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['budget_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payee_id'], ['budget_payees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_recurring_transactions_family_id'), 'budget_recurring_transactions', ['family_id'], unique=False)
    op.alter_column('budget_accounts', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('budget_accounts', 'offbudget',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False,
               existing_comment='Tracking account (not part of budget)')
    op.alter_column('budget_accounts', 'closed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('budget_accounts', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.add_column('budget_allocations', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True, comment='Month close timestamp (null = open)'))
    op.alter_column('budget_allocations', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('budget_allocations', 'budgeted_amount',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='Amount in cents',
               existing_nullable=False)
    op.alter_column('budget_categories', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('budget_categories', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('budget_categories', 'hidden',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('budget_categories', 'rollover_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('budget_categories', 'goal_amount',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False,
               existing_comment='Monthly goal in cents')
    op.alter_column('budget_category_groups', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('budget_category_groups', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('budget_category_groups', 'is_income',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('budget_category_groups', 'hidden',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('budget_payees', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('budget_sync_state', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('budget_sync_state_family_id_key', 'budget_sync_state', type_='unique')
    op.drop_index('ix_budget_sync_state_family_id', table_name='budget_sync_state')
    op.create_index(op.f('ix_budget_sync_state_family_id'), 'budget_sync_state', ['family_id'], unique=True)
    op.alter_column('budget_transactions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('budget_transactions', 'cleared',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('budget_transactions', 'reconciled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('budget_transactions', 'is_parent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False,
               existing_comment='Is this a split parent transaction?')
    op.alter_column('rewards', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('task_assignments', 'status',
               existing_type=postgresql.ENUM('pending', 'completed', 'overdue', 'cancelled', name='assignmentstatus'),
               server_default=None,
               existing_nullable=False)
    # Create the enum type explicitly before adding the column
    assignmenttype_enum = postgresql.ENUM('AUTO', 'FIXED', 'ROTATE', name='assignmenttype', create_type=True)
    assignmenttype_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('task_templates', sa.Column('assignment_type', sa.Enum('AUTO', 'FIXED', 'ROTATE', name='assignmenttype', create_type=False), server_default='AUTO', nullable=False))
    op.add_column('task_templates', sa.Column('assigned_user_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of user UUIDs for FIXED or ROTATE assignment types'))
    op.alter_column('task_templates', 'points',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('task_templates', 'interval_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('task_templates', 'is_bonus',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('task_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('task_templates', 'is_bonus',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('task_templates', 'interval_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('task_templates', 'points',
               existing_type=sa.INTEGER(),
               server_default=sa.text('10'),
               existing_nullable=False)
    op.drop_column('task_templates', 'assigned_user_ids')
    op.drop_column('task_templates', 'assignment_type')
    # Drop the enum type after removing the column
    postgresql.ENUM(name='assignmenttype').drop(op.get_bind(), checkfirst=True)
    op.alter_column('task_assignments', 'status',
               existing_type=postgresql.ENUM('pending', 'completed', 'overdue', 'cancelled', name='assignmentstatus'),
               server_default=sa.text("'pending'::assignmentstatus"),
               existing_nullable=False)
    op.alter_column('rewards', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('budget_transactions', 'is_parent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True,
               existing_comment='Is this a split parent transaction?')
    op.alter_column('budget_transactions', 'reconciled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('budget_transactions', 'cleared',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('budget_transactions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_budget_sync_state_family_id'), table_name='budget_sync_state')
    op.create_index('ix_budget_sync_state_family_id', 'budget_sync_state', ['family_id'], unique=False)
    op.create_unique_constraint('budget_sync_state_family_id_key', 'budget_sync_state', ['family_id'])
    op.alter_column('budget_sync_state', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('budget_payees', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('budget_category_groups', 'hidden',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('budget_category_groups', 'is_income',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('budget_category_groups', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('budget_category_groups', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('budget_categories', 'goal_amount',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True,
               existing_comment='Monthly goal in cents')
    op.alter_column('budget_categories', 'rollover_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=True)
    op.alter_column('budget_categories', 'hidden',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('budget_categories', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('budget_categories', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('budget_allocations', 'budgeted_amount',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_comment='Amount in cents',
               existing_nullable=False)
    op.alter_column('budget_allocations', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_column('budget_allocations', 'closed_at')
    op.alter_column('budget_accounts', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('budget_accounts', 'closed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('budget_accounts', 'offbudget',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True,
               existing_comment='Tracking account (not part of budget)')
    op.alter_column('budget_accounts', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_budget_recurring_transactions_family_id'), table_name='budget_recurring_transactions')
    op.drop_table('budget_recurring_transactions')
    op.drop_index(op.f('ix_budget_goals_family_id'), table_name='budget_goals')
    op.drop_table('budget_goals')
    op.drop_index(op.f('ix_budget_categorization_rules_family_id'), table_name='budget_categorization_rules')
    op.drop_table('budget_categorization_rules')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_id'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    # ### end Alembic commands ###
