"""add role field to family invitations

Revision ID: 6515f446212a
Revises: 8d9023cb4bad
Create Date: 2026-03-03 02:28:58.680324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6515f446212a'
down_revision = '8d9023cb4bad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family_invitations', sa.Column('role', sa.Enum('PARENT', 'CHILD', 'TEEN', name='userrole'), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE family_invitations SET role = 'CHILD' WHERE role IS NULL")
    # Now make it not nullable
    op.alter_column('family_invitations', 'role', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('family_invitations', 'role')
    # ### end Alembic commands ###
