"""Add soft delete fields to budget tables

Revision ID: 71e36cd7ea5a
Revises: 6515f446212a
Create Date: 2026-03-03 21:19:43.966192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e36cd7ea5a'
down_revision = '6515f446212a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_accounts', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp'))
    op.add_column('budget_accounts', sa.Column('deleted_by_id', sa.UUID(), nullable=True, comment='User who deleted this account'))
    op.create_index(op.f('ix_budget_accounts_deleted_at'), 'budget_accounts', ['deleted_at'], unique=False)
    op.create_foreign_key(None, 'budget_accounts', 'users', ['deleted_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('budget_categories', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp'))
    op.add_column('budget_categories', sa.Column('deleted_by_id', sa.UUID(), nullable=True, comment='User who deleted this category'))
    op.create_index(op.f('ix_budget_categories_deleted_at'), 'budget_categories', ['deleted_at'], unique=False)
    op.create_foreign_key(None, 'budget_categories', 'users', ['deleted_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('budget_category_groups', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp'))
    op.add_column('budget_category_groups', sa.Column('deleted_by_id', sa.UUID(), nullable=True, comment='User who deleted this group'))
    op.create_index(op.f('ix_budget_category_groups_deleted_at'), 'budget_category_groups', ['deleted_at'], unique=False)
    op.create_foreign_key(None, 'budget_category_groups', 'users', ['deleted_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('budget_transactions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp'))
    op.add_column('budget_transactions', sa.Column('deleted_by_id', sa.UUID(), nullable=True, comment='User who deleted this transaction'))
    op.create_index(op.f('ix_budget_transactions_deleted_at'), 'budget_transactions', ['deleted_at'], unique=False)
    op.create_foreign_key(None, 'budget_transactions', 'users', ['deleted_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'budget_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_budget_transactions_deleted_at'), table_name='budget_transactions')
    op.drop_column('budget_transactions', 'deleted_by_id')
    op.drop_column('budget_transactions', 'deleted_at')
    op.drop_constraint(None, 'budget_category_groups', type_='foreignkey')
    op.drop_index(op.f('ix_budget_category_groups_deleted_at'), table_name='budget_category_groups')
    op.drop_column('budget_category_groups', 'deleted_by_id')
    op.drop_column('budget_category_groups', 'deleted_at')
    op.drop_constraint(None, 'budget_categories', type_='foreignkey')
    op.drop_index(op.f('ix_budget_categories_deleted_at'), table_name='budget_categories')
    op.drop_column('budget_categories', 'deleted_by_id')
    op.drop_column('budget_categories', 'deleted_at')
    op.drop_constraint(None, 'budget_accounts', type_='foreignkey')
    op.drop_index(op.f('ix_budget_accounts_deleted_at'), table_name='budget_accounts')
    op.drop_column('budget_accounts', 'deleted_by_id')
    op.drop_column('budget_accounts', 'deleted_at')
    # ### end Alembic commands ###
