"""add family invitations table

Revision ID: 8d9023cb4bad
Revises: 4e13e6ee6325
Create Date: 2026-03-03 01:27:41.022345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d9023cb4bad'
down_revision = '4e13e6ee6325'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_invitations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('invited_email', sa.String(length=255), nullable=False),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=False),
    sa.Column('invitation_code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='invitationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_invitations_invitation_code'), 'family_invitations', ['invitation_code'], unique=True)
    op.create_index(op.f('ix_family_invitations_invited_email'), 'family_invitations', ['invited_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_family_invitations_invited_email'), table_name='family_invitations')
    op.drop_index(op.f('ix_family_invitations_invitation_code'), table_name='family_invitations')
    op.drop_table('family_invitations')
    # ### end Alembic commands ###
